### PR TITLE
Feature/traj_isclose

### PR DESCRIPTION
**Pull request by galjos**
Added isclose member function to `Trajectory`, `AtomicSystem` and `Cell`.

`__eq__` now calls `isclose` with default arguments.

### CODE REVIEW

**Comment by 97gamjak** [comment]
what happens if both atol and rtol are given?

**Comment by 97gamjak** [comment]
> what happens if both atol and rtol are given?

Or to put it in a different way. The numpy implementation has to default values - we use the same ones as `numpy.isclose`.

But how do they handle these values? Is it always the stricter value or the other one?

**Comment by galjos** [comment]
And, since we had `np.isclose` already implemented with with the default values, there is no real change in functionality.

**Comment by 97gamjak** [comment]
So actually I had a look at the numpy documentation. I think we should really reconsider at least the eq implementation:

For finite values, isclose uses the following equation to test whether two floating point values are equivalent.

```
absolute(a - b) <= (atol + rtol * absolute(b))
```
Unlike the built-in [math.isclose](https://docs.python.org/3/library/math.html#math.isclose), the above equation is not symmetric in a and b – it assumes b is the reference value – so that isclose(a, b) might be different from isclose(b, a). Furthermore, the default value of atol is not zero, and is used to determine what small values should be considered close to zero. The default value is appropriate for expected values of order unity: if the expected values are significantly smaller than one, it can result in false positives. atol should be carefully selected for the use case at hand. A zero value for atol will result in False if either a or b is zero.

**Comment by 97gamjak** [comment]
So what should we do now?

I had a quick look at the [`math.isclose`](https://docs.python.org/3/library/math.html) function and in my opinion, this would be the best way to go. The non-symmetry of the `numpy.isclose` definiton seems like sort of a "bug" of numpy. There exists an issue within the numpy repository [issue 10161](https://github.com/numpy/numpy/issues/10161), where the basic tenor of the discussions seems a bit similar to ours. My main conclusion when reading/analyszing the discussion within this **OPEN** issue is that they should have used the "*more correct*" implementation of `math.isclose` but now it is to late to change the current implementation as everything would break and they wouldn't be backward compatible anymore.

So my suggestion would be to implement the same `isclose` member functions as we did now, but using `math.isclose` along with their default values (`rel_tol=1e-09, abs_tol=0.0`), which would also ensure symmetry for the `__eq__` methods. After implementing these new routines, we should definitly write a new benchmark group in order to compare both implementations. If the `numpy.isclose` function is considerably faster we would have to discuss further on how critical the performance of these member function is and might be in future use cases.

What do you think @galjos ?

**Comment by galjos** [comment]
@97gamjak we could suggest to numpy to fix the isclose

**Comment by galjos** [comment]
In my opinion this is a bug on their side

**Comment by 97gamjak** [comment]
> @97gamjak we could suggest to numpy to fix the isclose

yes but if you read this issue, i think they have no intentions in closing or resolving this 😔

**Comment by galjos** [comment]
Obviously, this change could break alot of projects based on numpy. Although it would be correct to have the math implementation 🥲

**Comment by galjos** [comment]
I tried to include `math.isclose`, but imo the code is unreadable now:

```
        result = []
        for self_pos, other_pos in zip(self.pos, other.pos):
            for self_pos_i, other_pos_i in zip(self_pos, other_pos):
                result.append(
                    math.isclose(
                        self_pos_i, other_pos_i, rel_tol=rtol, abs_tol=atol
                    )
                )

        if not np.all(result):
            return False
```

**Comment by 97gamjak** [comment]
> I tried to include `math.isclose`, but imo the code is unreadable now:
> 
> ```
>         result = []
>         for self_pos, other_pos in zip(self.pos, other.pos):
>             for self_pos_i, other_pos_i in zip(self_pos, other_pos):
>                 result.append(
>                     math.isclose(
>                         self_pos_i, other_pos_i, rel_tol=rtol, abs_tol=atol
>                     )
>                 )
> 
>         if not np.all(result):
>             return False
> ```

How about doing something like this:

```
isclose_vectorized = np.vectorize(math.isclose)
np.all(isclose_vectorized(self.pos, other.pos))
```

**Comment by 97gamjak** [comment]
> > I tried to include `math.isclose`, but imo the code is unreadable now:
> > ```
> >         result = []
> >         for self_pos, other_pos in zip(self.pos, other.pos):
> >             for self_pos_i, other_pos_i in zip(self_pos, other_pos):
> >                 result.append(
> >                     math.isclose(
> >                         self_pos_i, other_pos_i, rel_tol=rtol, abs_tol=atol
> >                     )
> >                 )
> > 
> >         if not np.all(result):
> >             return False
> > ```
> 
> How about doing something like this:
> 
> ```
> isclose_vectorized = np.vectorize(math.isclose)
> np.all(isclose_vectorized(self.pos, other.pos, rel_tol=rtol, abs_tol=atol))
> ```
> 
> Probably best would be to define a function in utils (or somewhere else) like this:
> 
> ```
> def allclose_vectorized(a, b, rtol=..., atol=...):
>     isclose_vectorized = np.vectorize(math.isclose)
>     result = isclose_vectorized(a, b, rel_tol=rtol, abs_tol=atol)
>     return np.all(result)
> ```
> 
> Then, we could always use it like this:
> 
> ```
> allclose_vectorized(self.pos, other.pos, rtol=rtol, atol=atol)
> ```

I just added the described function in `utils.math` with the last commit.

**Comment by 97gamjak** [comment]
I just had a quick look at the `codecov CI` - Probably we never checked the detailed run results. The tests checking if the `baertype` approach works by setting the the environment to development in the bash script gives a total of **8 failed tests**.

This happens probably because the return value of the quick and dirty shell script hack is overwritten by the second run of pytest, which fully succeeds.

**Comment by 97gamjak** [comment]
> I just had a quick look at the `codecov CI` - Probably we never checked the detailed run results. The tests checking if the `baertype` approach works by setting the the environment to development in the bash script gives a total of **8 failed tests**.
> 
> This happens probably because the return value of the quick and dirty shell script hack is overwritten by the second run of pytest, which fully succeeds.

This issue has been resolved. The problem was that the `isclose` member function of `Trajectory` did not return a `bool` but a `np.boo_`. Apparently, `beartype` can't handle this, so I introduced a new type in `PQAnalysis.types` called `Bool`, which handles both. So if there is no need to distinguish between `bool` and `np.bool_`, we should always use the `PQAnalysis` specific type `Bool` and not `bool`.

**Pull request merged**
