### PR TITLE
Added ipynb as example for shake generation.

### PR DESCRIPTION
**Pull request by Lucky-Armin**
June 11, 2023 ape

### CODE REVIEW

**Comment by galjos** [comment]
@Lucky-Armin I don't see any notebook.

**Comment by Lucky-Armin** [comment]
I have overlooked the .ipynb file in the commit due to the .gitignore settings....

**Comment by galjos** [comment]
@Lucky-Armin would you be so kind an **clear** the output of the notebook.

**Comment by galjos** [comment]
@97gamjak I see, we have an error in the Pylint action.

**Comment by 97gamjak** [comment]
@galjos @Lucky-Armin 

Please note for the next time this shouldn't be a merge to main... should be included in dev - this is not worth a new tag - therefore, merging to dev

**Comment by 97gamjak** [comment]
> @97gamjak I see we have an error in the Pylint action.

Yes, I know this error. It only appears on pullnrequests from forked branches. Probaboy because the bot has nonwrite permissions on such repos.

**Comment by 97gamjak** [comment]
closes #94

**Pull request merged**
